force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testEventAttendeeHandler.cls
@isTest(SeeAllData=true)
public with sharing class testEventAttendeeHandler {
    
    @isTest
    static void testEventAttendeeHandler(){
        
        List<Attendee__c> attendee =  testGenericData.createAttendee(2);
        insert attendee;

        List<Event_Organizer__c> eventOrganizer = testGenericData.createEventOrganizer(2);
        insert eventOrganizer;

        List<Event__c> event = testGenericData.createEvent(2, eventOrganizer);
        insert event;

        List<Event_Attendee__c> eventAttendee = testGenericData.createEventAttendee(2, attendee, event);
        insert eventAttendee;
    }
}