force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testDeleteOldEvent.cls
@isTest
public with sharing class testDeleteOldEvent {

    @isTest
    static void testDeleteOldEvent() {

        List<Event_Organizer__c> eventOrganizer = testGenericData.createEventOrganizer(1);
        insert eventOrganizer;

        List<Event__c> event = testGenericData.createEvent(1, eventOrganizer);
        insert event;
        
        Event__c updateEvent = [SELECT Id, Name, Live__c, End_Date_Time__c from Event__c WHERE Id =: event[0].Id];
        updateEvent.Live__c = TRUE;
        updateEvent.Start_Date_Time__c = System.now().addDays(-80);
        updateEvent.End_Date_Time__c = System.now().addDays(-70);
        update updateEvent;

        Test.startTest();

        deleteOldEvents doe = new deleteOldEvents();
        System.schedule('deleteOldEvents', '0 0 23 * * ?', doe);

        Test.stopTest();
    }
}