force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Event#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/deleteOldEvents.cls
global class deleteOldEvents implements Database.Batchable<SObject>, Schedulable, Database.Stateful {

    List<String> eventName = new List<String>();
    global Database.QueryLocator start (Database.BatchableContext bc) {

        return Database.getQueryLocator([SELECT Id, Name, Live__c, End_Date_Time__c from Event__c]);
    }

    global void execute (Database.BatchableContext bc, List<Event__c> event) {

        List<Event__c> deleteEvents = eventHandler.deleteOldEventsExecute(event);
        
        for (Event__c finishEvents: deleteEvents) {
            eventName.add(finishEvents.Name);
        }
        delete deleteEvents;
    }

    global void finish (Database.BatchableContext bc) {

        eventHandler.deleteOldEventsFinish(eventName);
    }

    global void execute(SchedulableContext sc) {

        deleteOldEvents doe = new deleteOldEvents();
        Database.executeBatch(doe);
    }
}